export { default as Amount } from './texts/Amount'
export { default as Label } from './texts/Label'
export { default as Paragraph } from './texts/Paragraph'
export { default as PrimaryTitle } from './texts/PrimaryTitle'
export { default as SecondaryTitle } from './texts/SecondaryTitle'
export { default as Subtitle } from './texts/Subtitle'
export { default as TextLabel } from './texts/TextLabel'
